name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy
      confirmation:
        description: 'Type "CONFIRM" to proceed with production deployment'
        required: true
        type: string

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == 'CONFIRM'
    steps:
      - name: Production Deployment Confirmed
        run: echo "✅ Production deployment confirmed"
    
  call-deploy:
    needs: deploy-prod
    uses: ./.github/workflows/deploy.yaml
    with:
      workspace: production
      action: ${{ github.event.inputs.action }}
    secrets: inherit
